from typing import Any, Dict, List


def extract_information(entities: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Convert NER entities into structured medical information.

    Input:
        List of entities generated by the NER module.

    Output:
        Structured information containing:
        - symptoms
        - severity
        - duration
        - frequency
        - body parts
        - triggers
        - medications
        - conditions
    """

    symptoms = []
    severity = None
    duration = None
    frequency = []
    body_parts = []
    triggers = []
    medications = []
    conditions = []

    # -------------------------------------------------
    # Process extracted entities
    # -------------------------------------------------

    for entity in entities:

        entity_text = entity.get("text", "").strip()
        entity_type = entity.get("type", "").upper()

        if not entity_text:
            continue

        # ---------------------------------------------
        # Symptoms
        # ---------------------------------------------

        if entity_type == "SYMPTOM":

            if entity_text.lower() not in [
                symptom.lower() for symptom in symptoms
            ]:
                symptoms.append(entity_text)

        # ---------------------------------------------
        # Severity
        # ---------------------------------------------

        elif entity_type == "SEVERITY":

            severity = entity_text

        # ---------------------------------------------
        # Duration
        # ---------------------------------------------

        elif entity_type == "DURATION":

            duration = entity_text

        # ---------------------------------------------
        # Frequency
        # ---------------------------------------------

        elif entity_type == "FREQUENCY":

            if entity_text.lower() not in [
                item.lower() for item in frequency
            ]:
                frequency.append(entity_text)

        # ---------------------------------------------
        # Body Parts
        # ---------------------------------------------

        elif entity_type == "BODY_PART":

            if entity_text.lower() not in [
                item.lower() for item in body_parts
            ]:
                body_parts.append(entity_text)

        # ---------------------------------------------
        # Triggers
        # ---------------------------------------------

        elif entity_type == "TRIGGER":

            if entity_text.lower() not in [
                item.lower() for item in triggers
            ]:
                triggers.append(entity_text)

        # ---------------------------------------------
        # Medications
        # ---------------------------------------------

        elif entity_type == "MEDICATION":

            if entity_text.lower() not in [
                item.lower() for item in medications
            ]:
                medications.append(entity_text)

        # ---------------------------------------------
        # Existing medical conditions
        # ---------------------------------------------

        elif entity_type == "DISEASE":

            if entity_text.lower() not in [
                item.lower() for item in conditions
            ]:
                conditions.append(entity_text)

    # -------------------------------------------------
    # Return structured medical information
    # -------------------------------------------------

    return {
        "symptoms": symptoms,
        "severity": severity,
        "duration": duration,
        "frequency": frequency,
        "body_parts": body_parts,
        "triggers": triggers,
        "medications": medications,
        "conditions": conditions
    }