import React from 'react';
import { ShieldAlert, X, PhoneCall, AlertTriangle, CheckCircle } from 'lucide-react';

interface DisclaimerModalProps {
  onClose: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ onClose }) => {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
      <div className="relative w-full max-w-2xl bg-white dark:bg-slate-900 rounded-2xl shadow-2xl border border-slate-200 dark:border-slate-800 p-6 space-y-5 max-h-[85vh] overflow-y-auto text-slate-800 dark:text-slate-200">
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
          <div className="flex items-center gap-2 text-rose-600 dark:text-rose-400">
            <ShieldAlert className="w-5 h-5" />
            <h3 className="text-lg font-bold">MediQuery Medical & Educational Disclaimer</h3>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-4 text-xs sm:text-sm leading-relaxed">
          <div className="p-4 bg-rose-50 dark:bg-rose-950/40 rounded-xl border border-rose-200 dark:border-rose-900 text-rose-900 dark:text-rose-200 space-y-2">
            <div className="flex items-center gap-2 font-bold text-sm">
              <AlertTriangle className="w-4 h-4" />
              <span>Not Medical Advice or Clinical Diagnosis</span>
            </div>
            <p>
              MediQuery is an educational decision-support software application. It is NOT a medical device, diagnostic test, or clinical authority.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-slate-900 dark:text-white mb-1.5">
              1. Decision-Support Boundary
            </h4>
            <p className="text-slate-600 dark:text-slate-400">
              The descriptions, symptom overlap indicators, and retrieved health information generated by this tool are designed exclusively to facilitate informed educational discussions between individuals and their licensed healthcare providers. MediQuery does not prescribe treatments, medications, or surgical interventions.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-slate-900 dark:text-white mb-1.5">
              2. Emergency Medical Conditions
            </h4>
            <p className="text-slate-600 dark:text-slate-400">
              If you or someone in your vicinity is experiencing severe chest pain, sudden numbness or paralysis, severe shortness of breath, loss of consciousness, heavy uncontrolled bleeding, or signs of anaphylaxis, do NOT wait for software analysis. Contact your local emergency services (e.g., 911, 112, 999) or visit the nearest emergency medical facility immediately.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-slate-900 dark:text-white mb-1.5">
              3. Limitation of Liability
            </h4>
            <p className="text-slate-600 dark:text-slate-400">
              Neither the project authors, faculty evaluators, nor academic institution assume liability for any actions taken or not taken based on the information provided by this demonstration software.
            </p>
          </div>
        </div>

        <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2 bg-slate-800 hover:bg-slate-900 text-white rounded-xl text-xs sm:text-sm font-semibold cursor-pointer"
          >
            I Understand & Acknowledge
          </button>
        </div>
      </div>
    </div>
  );
};
